# Niri config.kdl generation
{ config
, pkgs
, lib
, hostSpec
, ...
}:
let
  terminal = hostSpec.defaultTerminal;
  browser = hostSpec.defaultBrowser;
  barChoice = hostSpec.barChoice;
  wallpaper = toString hostSpec.wallpaper;

  launcherCommand =
    if barChoice == "noctalia"
    then ''"noctalia-shell" "ipc" "call" "launcher" "toggle"''
    else ''"fuzzel"'';

  noctaliaKeybinds = lib.optionalString (barChoice == "noctalia") ''
    // === Noctalia Controls ===
    Mod+Comma {
        spawn "noctalia-shell" "ipc" "call" "settings" "toggle";
    }
    Mod+Alt+S {
        spawn "noctalia-shell" "ipc" "call" "settings" "toggle";
    }
    Mod+Shift+C {
        spawn "noctalia-shell" "ipc" "call" "controlCenter" "toggle";
    }
  '';

  barStartupCommand =
    if barChoice == "noctalia"
    then ''spawn-at-startup "noctalia-shell"''
    else ''// ${barChoice} started via systemd service'';
in
{
  # Use the niri-flake's config option to avoid conflicting with its
  # home-manager module (which also manages .config/niri/config.kdl).
  programs.niri.config = ''
    // Niri Configuration for ${hostSpec.hostName}
    // Generated by NixOS home-manager

    // ── Input ──────────────────────────────────────────────────────
    input {
        keyboard {
            xkb {
            }
            numlock
        }
        touchpad {
            natural-scroll
        }
        mouse {
            accel-profile "adaptive"
            accel-speed 1.0
        }
        trackpoint {
        }

        focus-follows-mouse
        warp-mouse-to-focus
    }

    // ── Layout ─────────────────────────────────────────────────────
    layout {
        gaps 9

        center-focused-column "never"
        always-center-single-column

        preset-column-widths {
            proportion 0.25
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
            proportion 1.0
        }

        default-column-width { proportion 0.5; }

        preset-window-heights {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
        }

        border {
            width 2
            active-color "#cba6f7"
            inactive-color "#45475a"
            urgent-color "#f5c2e7"
        }

        focus-ring {
            off
        }

        shadow {
            softness 30
            spread 5
            offset x=0 y=5
            color "#0007"
        }

        struts {
        }
    }

    // ── Overview ───────────────────────────────────────────────────
    overview {
        backdrop-color "#1e1e2e"

        workspace-shadow {
            softness 40
            spread 10
            offset x=0 y=10
            color "#00000050"
        }

        zoom 0.5
    }

    // ── Animations ─────────────────────────────────────────────────
    animations {
        workspace-switch {
            spring damping-ratio=0.80 stiffness=523 epsilon=0.0001
        }
        window-open {
            duration-ms 150
            curve "ease-out-expo"
        }
        window-close {
            duration-ms 150
            curve "ease-out-quad"
        }
        horizontal-view-movement {
            spring damping-ratio=0.85 stiffness=423 epsilon=0.0001
        }
        window-movement {
            spring damping-ratio=0.75 stiffness=323 epsilon=0.0001
        }
        window-resize {
            spring damping-ratio=0.85 stiffness=423 epsilon=0.0001
        }
        config-notification-open-close {
            spring damping-ratio=0.65 stiffness=923 epsilon=0.001
        }
        screenshot-ui-open {
            duration-ms 200
            curve "ease-out-quad"
        }
        overview-open-close {
            spring damping-ratio=0.85 stiffness=800 epsilon=0.0001
        }
    }

    // ── Window Rules ───────────────────────────────────────────────
    // Firefox picture-in-picture as floating
    window-rule {
        match app-id=r#"firefox$"# title="^Picture-in-Picture$"
        open-floating true
    }

    // Global window styling
    window-rule {
        geometry-corner-radius 9
        clip-to-geometry true
        draw-border-with-background false
    }

    // Opacity rules
    window-rule {
        match app-id=r#"^(kitty|thunar|org\.telegram\.desktop|discord|vesktop|org\.gnome\.Nautilus)$"#
        opacity 0.9
    }

    window-rule {
        match app-id=r#"^(zen-beta|dev\.zed\.Zed)$"#
        opacity 0.98
        default-column-width { proportion 0.75; }
    }

    window-rule {
        match app-id=r#"^(steam)$"#
        opacity 0.95
    }

    // ── Keybindings ────────────────────────────────────────────────
    binds {
        // === System & Overview ===
        Mod+X repeat=false { toggle-overview; }
        Mod+O repeat=false { toggle-overview; }
        Mod+Shift+Slash { show-hotkey-overlay; }

        // === Application Launchers ===
        Mod+T { spawn "${terminal}"; }
        Mod+Return { spawn "${terminal}"; }
        Mod+Y { spawn "fuzzel"; }
        Mod+Space { spawn ${launcherCommand}; }

        // === Audio Controls ===
        XF86AudioRaiseVolume allow-when-locked=true {
            spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%+" "-l" "1.0";
        }
        XF86AudioLowerVolume allow-when-locked=true {
            spawn "wpctl" "set-volume" "@DEFAULT_AUDIO_SINK@" "5%-";
        }
        XF86AudioMute allow-when-locked=true {
            spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SINK@" "toggle";
        }
        XF86AudioMicMute allow-when-locked=true {
            spawn "wpctl" "set-mute" "@DEFAULT_AUDIO_SOURCE@" "toggle";
        }

        // === Brightness Controls ===
        XF86MonBrightnessUp allow-when-locked=true {
            spawn "brightnessctl" "set" "5%+";
        }
        XF86MonBrightnessDown allow-when-locked=true {
            spawn "brightnessctl" "set" "5%-";
        }
        XF86KbdBrightnessUp allow-when-locked=true {
            spawn "brightnessctl" "--device=*::kbd_backlight" "set" "5%+";
        }
        XF86KbdBrightnessDown allow-when-locked=true {
            spawn "brightnessctl" "--device=*::kbd_backlight" "set" "5%-";
        }

        ${noctaliaKeybinds}

        // === Security ===
        Mod+Shift+Q { quit; }

        // === Window Management ===
        Mod+Q repeat=false { close-window; }
        Mod+Alt+F { maximize-column; }
        Mod+Shift+F { fullscreen-window; }
        Mod+W { toggle-window-floating; }
        Mod+Ctrl+W { switch-focus-between-floating-and-tiling; }
        Mod+V { toggle-column-tabbed-display; }

        // === Focus Navigation ===
        Mod+Left  { focus-column-left; }
        Mod+Down  { focus-window-down; }
        Mod+Up    { focus-window-up; }
        Mod+Right { focus-column-right; }
        Mod+H     { focus-column-left; }
        Mod+J     { focus-window-down; }
        Mod+K     { focus-window-up; }
        Mod+L     { focus-column-right; }

        // === Window Movement ===
        Mod+Shift+Left  { move-column-left; }
        Mod+Shift+Down  { move-window-down; }
        Mod+Shift+Up    { move-window-up; }
        Mod+Shift+Right { move-column-right; }
        Mod+Shift+H     { move-column-left; }
        Mod+Shift+J     { move-window-down; }
        Mod+Shift+K     { move-window-up; }
        Mod+Shift+L     { move-column-right; }

        // === Column Navigation ===
        Mod+Home { focus-column-first; }
        Mod+End  { focus-column-last; }
        Mod+Ctrl+Home { move-column-to-first; }
        Mod+Ctrl+End  { move-column-to-last; }

        // === Monitor Navigation ===
        Mod+Ctrl+Left  { focus-monitor-left; }
        Mod+Ctrl+Right { focus-monitor-right; }
        Mod+Ctrl+H     { focus-monitor-left; }
        Mod+Ctrl+J     { focus-monitor-down; }
        Mod+Ctrl+K     { focus-monitor-up; }
        Mod+Ctrl+L     { focus-monitor-right; }

        // === Move to Monitor ===
        Mod+Shift+Ctrl+Left  { move-column-to-monitor-left; }
        Mod+Shift+Ctrl+Down  { move-column-to-monitor-down; }
        Mod+Shift+Ctrl+Up    { move-column-to-monitor-up; }
        Mod+Shift+Ctrl+Right { move-column-to-monitor-right; }
        Mod+Shift+Ctrl+H     { move-column-to-monitor-left; }
        Mod+Shift+Ctrl+J     { move-column-to-monitor-down; }
        Mod+Shift+Ctrl+K     { move-column-to-monitor-up; }
        Mod+Shift+Ctrl+L     { move-column-to-monitor-right; }

        // === Workspace Navigation ===
        Mod+U                { focus-workspace-down; }
        Mod+I                { focus-workspace-up; }
        Mod+Ctrl+Down        { focus-workspace-down; }
        Mod+Ctrl+Up          { focus-workspace-up; }
        Mod+Ctrl+U    { move-column-to-workspace-down; }
        Mod+Ctrl+I    { move-column-to-workspace-up; }

        // === Move Workspaces ===
        Mod+Shift+Page_Down { move-workspace-down; }
        Mod+Shift+Page_Up   { move-workspace-up; }
        Mod+Shift+U         { move-workspace-down; }
        Mod+Shift+I         { move-workspace-up; }

        // === Mouse Wheel Navigation ===
        Mod+WheelScrollDown      cooldown-ms=150 { focus-workspace-down; }
        Mod+WheelScrollUp        cooldown-ms=150 { focus-workspace-up; }
        Mod+Ctrl+WheelScrollDown cooldown-ms=150 { move-column-to-workspace-down; }
        Mod+Ctrl+WheelScrollUp   cooldown-ms=150 { move-column-to-workspace-up; }

        Mod+WheelScrollRight      { focus-column-right; }
        Mod+WheelScrollLeft       { focus-column-left; }
        Mod+Ctrl+WheelScrollRight { move-column-right; }
        Mod+Ctrl+WheelScrollLeft  { move-column-left; }

        Mod+Shift+WheelScrollDown      { focus-column-right; }
        Mod+Shift+WheelScrollUp        { focus-column-left; }
        Mod+Ctrl+Shift+WheelScrollDown { move-column-right; }
        Mod+Ctrl+Shift+WheelScrollUp   { move-column-left; }

        // === Numbered Workspaces ===
        Mod+1 { focus-workspace 1; }
        Mod+2 { focus-workspace 2; }
        Mod+3 { focus-workspace 3; }
        Mod+4 { focus-workspace 4; }
        Mod+5 { focus-workspace 5; }
        Mod+6 { focus-workspace 6; }
        Mod+7 { focus-workspace 7; }
        Mod+8 { focus-workspace 8; }
        Mod+9 { focus-workspace 9; }
        Mod+Shift+1 { move-column-to-workspace 1; }
        Mod+Shift+2 { move-column-to-workspace 2; }
        Mod+Shift+3 { move-column-to-workspace 3; }
        Mod+Shift+4 { move-column-to-workspace 4; }
        Mod+Shift+5 { move-column-to-workspace 5; }
        Mod+Shift+6 { move-column-to-workspace 6; }
        Mod+Shift+7 { move-column-to-workspace 7; }
        Mod+Shift+8 { move-column-to-workspace 8; }
        Mod+Shift+9 { move-column-to-workspace 9; }

        // === Column Management ===
        Mod+BracketLeft  { consume-or-expel-window-left; }
        Mod+BracketRight { consume-or-expel-window-right; }
        Mod+Period { expel-window-from-column; }

        // === Sizing & Layout ===
        Mod+R { switch-preset-column-width; }
        Mod+Shift+R { switch-preset-window-height; }
        Mod+Ctrl+R { reset-window-height; }
        Mod+Ctrl+F { expand-column-to-available-width; }
        Mod+Ctrl+C { center-column; }

        // === Manual Sizing ===
        Mod+Minus { set-column-width "-10%"; }
        Mod+Equal { set-column-width "+10%"; }
        Mod+Shift+Minus { set-window-height "-10%"; }
        Mod+Shift+Equal { set-window-height "+10%"; }

        // === Screenshots ===
        Mod+Shift+S { screenshot; }
        Print { screenshot; }
        Ctrl+Print { screenshot-screen; }
        Alt+Print { screenshot-window; }

        // === System Controls ===
        Mod+Alt+P { power-off-monitors; }

        // === Custom Application Launchers ===
        Alt+Ctrl+B { spawn "${browser}"; }
        Alt+Ctrl+G { spawn "thunar"; }

        // === Color picker ===
        Mod+C { spawn-sh "niri msg pick-color | grep 'Hex:' | cut -d' ' -f2 | wl-copy"; }

        // === Dynamic Cast ===
        Mod+P { set-dynamic-cast-monitor; }
        Mod+Shift+P { set-dynamic-cast-window; }
        Mod+Ctrl+P { clear-dynamic-cast-target; }
    }

    // ── Startup ────────────────────────────────────────────────────
    spawn-at-startup "bash" "-c" "wl-paste --watch cliphist store &"
    ${barStartupCommand}
    spawn-at-startup "xwayland-satellite"
    spawn-at-startup "bash" "-c" "swww-daemon && sleep 1 && swww img '${wallpaper}'"
    spawn-at-startup "kanshi"

    // ── Environment ────────────────────────────────────────────────
    environment {
        XDG_CURRENT_DESKTOP "niri"
        GTK_USE_PORTAL "1"
        MOZ_ENABLE_WAYLAND "1"
        QT_QPA_PLATFORM "wayland"
        ELECTRON_OZONE_PLATFORM_HINT "wayland"
        TERMINAL "${terminal}"
        XCURSOR_THEME "Bibata-Modern-Ice"
        XCURSOR_SIZE "24"

        // NVIDIA Gaming Optimizations
        __GL_GSYNC_ALLOWED "1"
        __GL_VRR_ALLOWED "1"
        PROTON_ENABLE_NVAPI "1"
        PROTON_HIDE_NVIDIA_GPU "0"
        PROTON_ENABLE_NGX_UPDATER "1"
    }

    hotkey-overlay {
        skip-at-startup
    }

    config-notification {
        disable-failed
    }

    gestures {
        hot-corners {
            off
        }
    }

    prefer-no-csd

    screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"
  '';
}
